encoding: UTF-8

# SEO相关信息
title: 王传军的技术博客
description: 王传军的技术博客，学习，分享，成长。
keywords: WangChuanjun,Blog,Java,Go,CloudNative
author: 王传军
footerText: 'Copyright@<a href="mailto:wcj@zju.edu.cn">王传军</a>'

# 这些不要动
permalink: blog/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
exclude: ['README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh', '.gitignore']

future: true
timezone: Asia/Shanghai

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://uptechnic.github.io'
baseurl: ''

# 留言地址，使用github的讨论功能
discussions: https://github.com/uptechnic/uptechnic.github.io/discussions

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html
  - title: 友链
    url: /pages/links.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 当然我在扯淡 - 王垠
    url: https://www.yinwang.org/
